language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jaykay82/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jaykay82/docker-react npm run test